spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      database: account
      authentication-database: admin
management:
  endpoint:
    health:
      enabled: true