### GET acounts
GET localhost:8080/api/reactive/accounts
Content-Type: application/json

### POST account
POST localhost:8080/api/reactive/account
Content-Type: application/json

{
  "firstName": "iljun",
  "lastName": "won",
  "email": "sumusb34@gmail.com"
}

### GET account
GET localhost:8080/api/reactive/account/cc3bef07-b008-40df-8b5a-057535d29784
Content-Type: application/json

### PUT account
PUT localhost:8080/api/reactive/account/cc3bef07-b008-40df-8b5a-057535d29784
Content-Type: application/json

{
  "firstName": "iljun2",
  "lastName": "won2"
}

### DELETE Account
DELETE localhost:8080/api/reactive/account/cc3bef07-b008-40df-8b5a-057535d29784
Content-Type: application/json